version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-bai06
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: userwp
      MYSQL_PASSWORD: passwp
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress-bai06
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: userwp
      WORDPRESS_DB_PASSWORD: passwp
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data:
