# Sử dụng Nginx làm base image
FROM nginx:latest

# Copy file index.html vào thư mục chứa website của Nginx
COPY index.html /usr/share/nginx/html/index.html

# Mở cổng 80 để truy cập trang web
EXPOSE 80
