version: '3.8'

services:
  nodejs-app:
    build: .
    container_name: nodejs-app
    ports:
      - "3000:3000"
    networks:
      - nodejs-network

networks:
  nodejs-network:
    driver: bridge
